name: Deploy to Cert

on:
  push:
    branches:
      - main

permissions:
  contents: write
  checks: write
  pull-requests: write
  packages: write
  id-token: write

jobs:
  pipeline:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    uses: Codehunters-IO/ci-templates/.github/workflows/krakend-main-pipeline.yml@v1
    with:
      run_commit_lint: false
      run_build: true
      run_test: true
      run_artifact: true
      run_deploy: true
      run_cleanup: false
      run_release: false
      deploy_target: 'ec2-vpn'
      environment: 'cert'
    secrets: inherit
